namespace SqlConsole.Host.Configuration
{
    class SqlSettings
    {
        public Microsoft.Data.SqlClient.PoolBlockingPeriod? PoolBlockingPeriod { get; set; }
        public Microsoft.Data.SqlClient.ApplicationIntent? ApplicationIntent { get; set; }
        public System.String? ApplicationName { get; set; }
        public System.String? AttachDBFilename { get; set; }
        public System.Int32? ConnectTimeout { get; set; }
        public System.String? CurrentLanguage { get; set; }
        public System.String? DataSource { get; set; }
        public System.Boolean? Encrypt { get; set; }
        public Microsoft.Data.SqlClient.SqlConnectionColumnEncryptionSetting? ColumnEncryptionSetting { get; set; }
        public System.String? EnclaveAttestationUrl { get; set; }
        public Microsoft.Data.SqlClient.SqlConnectionAttestationProtocol? AttestationProtocol { get; set; }
        public System.Boolean? TrustServerCertificate { get; set; }
        public System.Boolean? Enlist { get; set; }
        public System.String? FailoverPartner { get; set; }
        public System.String? InitialCatalog { get; set; }
        public System.Boolean? IntegratedSecurity { get; set; }
        public Microsoft.Data.SqlClient.SqlAuthenticationMethod? Authentication { get; set; }
        public System.Int32? LoadBalanceTimeout { get; set; }
        public System.Int32? MaxPoolSize { get; set; }
        public System.Int32? ConnectRetryCount { get; set; }
        public System.Int32? ConnectRetryInterval { get; set; }
        public System.Int32? MinPoolSize { get; set; }
        public System.Boolean? MultipleActiveResultSets { get; set; }
        public System.Boolean? MultiSubnetFailover { get; set; }
        public System.Int32? PacketSize { get; set; }
        public System.String? Password { get; set; }
        public System.Boolean? PersistSecurityInfo { get; set; }
        public System.Boolean? Pooling { get; set; }
        public System.Boolean? Replication { get; set; }
        public System.String? TransactionBinding { get; set; }
        public System.String? TypeSystemVersion { get; set; }
        public System.String? UserID { get; set; }
        public System.Boolean? UserInstance { get; set; }
        public System.String? WorkstationID { get; set; }
    }
    class SqliteSettings
    {
        public System.String? DataSource { get; set; }
        public Microsoft.Data.Sqlite.SqliteOpenMode? Mode { get; set; }
        public Microsoft.Data.Sqlite.SqliteCacheMode? Cache { get; set; }
        public System.String? Password { get; set; }
        public System.Boolean? RecursiveTriggers { get; set; }
    }
    class OracleSettings
    {
        public System.String? ProxyUserId { get; set; }
        public System.String? ProxyPassword { get; set; }
        public System.String? DBAPrivilege { get; set; }
        public System.String? UserID { get; set; }
        public System.String? DataSource { get; set; }
        public System.String? Password { get; set; }
        public System.Int32? MaxPoolSize { get; set; }
        public System.Int32? MinPoolSize { get; set; }
        public System.Int32? IncrPoolSize { get; set; }
        public System.Int32? DecrPoolSize { get; set; }
        public System.Int32? ConnectionLifeTime { get; set; }
        public System.Int32? StatementCacheSize { get; set; }
        public System.Boolean? SelfTuning { get; set; }
        public System.Int32? ConnectionTimeout { get; set; }
        public System.Boolean? PersistSecurityInfo { get; set; }
        public System.String? Enlist { get; set; }
        public System.Boolean? MetadataPooling { get; set; }
        public System.Boolean? Pooling { get; set; }
        public System.Boolean? ValidateConnection { get; set; }
        public System.Boolean? StatementCachePurge { get; set; }
        public System.Boolean? HAEvents { get; set; }
        public System.Boolean? LoadBalancing { get; set; }
        public System.Boolean? ContextConnection { get; set; }
        public System.String? PromotableTransaction { get; set; }
        public System.String? TnsAdmin { get; set; }
        public System.String? WalletLocation { get; set; }
    }
    class DB2Settings
    {
        public System.String? Database { get; set; }
        public System.String? UserID { get; set; }
        public System.String? Password { get; set; }
        public System.String? Server { get; set; }
        public System.Boolean? Pooling { get; set; }
        public System.Int32? MinPoolSize { get; set; }
        public System.Int32? MaxPoolSize { get; set; }
        public System.Boolean? ConnectionReset { get; set; }
        public System.Int32? ConnectionLifeTime { get; set; }
        public System.Boolean? Enlist { get; set; }
        public System.Boolean? PersistSecurityInfo { get; set; }
        public System.Boolean? ConnStrPwdEncrypt { get; set; }
        public System.Boolean? EnsureDefaultDFRM { get; set; }
        public System.Int32? Connect_Timeout { get; set; }
        public System.Int32? QueryTimeout { get; set; }
        public System.String? IsolationLevel { get; set; }
        public System.String? CurrentSchema { get; set; }
        public System.String? CLISchema { get; set; }
        public System.String? SysSchema { get; set; }
        public System.String? DBName { get; set; }
        public System.String? TableType { get; set; }
        public System.String? SchemaList { get; set; }
        public System.String? LibraryList { get; set; }
        public System.Int32? MapDate { get; set; }
        public System.Int32? MapTime { get; set; }
        public System.Int32? MapTimestamp { get; set; }
        public System.Int32? StaticLatch { get; set; }
        public System.Int32? Graphic { get; set; }
        public System.Int32? ConvertToLong { get; set; }
        public System.String? Authentication { get; set; }
        public System.String? Instance { get; set; }
        public System.Int32? Interrupt { get; set; }
        public System.String? ServerType { get; set; }
        public System.Boolean? HostVarParameters { get; set; }
        public System.String? ClientEncAlg { get; set; }
        public System.Boolean? DelimIdent { get; set; }
        public System.String? executionMode { get; set; }
        public System.String? captureMode { get; set; }
        public System.String? pureQueryXML { get; set; }
        public System.String? traceFile { get; set; }
        public System.Boolean? allowDynamicSQL { get; set; }
        public System.Boolean? capturedOnly { get; set; }
        public System.Boolean? enableDynamicSQLReplacement { get; set; }
        public System.Int32? maxNonParmSQL { get; set; }
        public System.String? sqlLiteralSubstitution { get; set; }
        public System.String? traceLevel { get; set; }
        public System.String? propertiesGroupId { get; set; }
        public System.String? pureQueryXmlRepository { get; set; }
        public System.String? repositoryRequired { get; set; }
        public System.Int32? CodePage { get; set; }
        public System.String? WalletID { get; set; }
        public System.String? WalletPwd { get; set; }
        public System.String? TrustedContextSystemUserID { get; set; }
        public System.String? TrustedContextSystemPassword { get; set; }
        public System.String? TrustedContextUserRegistryName { get; set; }
        public System.String? Security { get; set; }
        public System.String? SSLClientKeystoredb { get; set; }
        public System.String? SSLClientKeystash { get; set; }
        public System.String? SSLClientLabel { get; set; }
        public System.String? SSLClientKeystoreDBPassword { get; set; }
        public System.String? ConcurrentAccessResolution { get; set; }
        public System.String? StatementConcentrator { get; set; }
        public System.Boolean? DisableCursorHold { get; set; }
        public System.Boolean? RetrieveXmlInBinaryFormat { get; set; }
        public System.Boolean? SkipSynonymProcessing { get; set; }
        public System.String? DB2Explain { get; set; }
        public System.String? ClientAccountingString { get; set; }
        public System.String? ClientApplicationName { get; set; }
        public System.String? ClientUserID { get; set; }
        public System.String? ClientWorkstationName { get; set; }
        public System.String? ProgramId { get; set; }
        public System.String? ProgramName { get; set; }
        public System.String? SessionTimeZone { get; set; }
        public System.String? InternalProperty9 { get; set; }
        public System.String? CurrentSQLID { get; set; }
        public System.String? FitHighPrecisionType { get; set; }
        public System.String? TargetPrincipal { get; set; }
        public System.Boolean? RetryParameterBindingOnError { get; set; }
        public System.Int32? ConnectNodeNumber { get; set; }
        public System.String? CurrentPackageSet { get; set; }
        public System.String? NewPWD { get; set; }
        public System.Boolean? EnableEFCaseSensitivity { get; set; }
        public System.String? ClientCorrelationToken { get; set; }
        public System.String? CurrentFunctionPath { get; set; }
        public System.String? SSLServerCertificate { get; set; }
        public System.String? Db2dumpSQLCodes { get; set; }
        public System.String? Db2DumpSQLCodesInterval { get; set; }
        public System.String? FetchBufferSize { get; set; }
    }
    class MySqlSettings
    {
        public System.String? PipeName { get; set; }
        public System.Boolean? UseCompression { get; set; }
        public System.Boolean? AllowBatch { get; set; }
        public System.Boolean? Logging { get; set; }
        public System.String? SharedMemoryName { get; set; }
        public System.UInt32? DefaultCommandTimeout { get; set; }
        public System.UInt32? ConnectionTimeout { get; set; }
        public System.Boolean? AllowLoadLocalInfile { get; set; }
        public System.Boolean? PersistSecurityInfo { get; set; }
        public System.Boolean? IntegratedSecurity { get; set; }
        public System.Boolean? AllowPublicKeyRetrieval { get; set; }
        public System.Boolean? AllowZeroDateTime { get; set; }
        public System.Boolean? ConvertZeroDateTime { get; set; }
        public System.Boolean? UseUsageAdvisor { get; set; }
        public System.UInt32? ProcedureCacheSize { get; set; }
        public System.Boolean? UsePerformanceMonitor { get; set; }
        public System.Boolean? IgnorePrepare { get; set; }
        public System.Boolean? AutoEnlist { get; set; }
        public System.Boolean? IncludeSecurityAsserts { get; set; }
        public System.Boolean? RespectBinaryFlags { get; set; }
        public System.Boolean? TreatTinyAsBoolean { get; set; }
        public System.Boolean? AllowUserVariables { get; set; }
        public System.Boolean? InteractiveSession { get; set; }
        public System.Boolean? FunctionsReturnString { get; set; }
        public System.Boolean? UseAffectedRows { get; set; }
        public System.Boolean? OldGuids { get; set; }
        public System.Boolean? SqlServerMode { get; set; }
        public System.Boolean? TableCaching { get; set; }
        public System.Int32? DefaultTableCacheAge { get; set; }
        public System.Boolean? CheckParameters { get; set; }
        public System.Boolean? Replication { get; set; }
        public System.String? ExceptionInterceptors { get; set; }
        public System.String? CommandInterceptors { get; set; }
        public System.UInt32? ConnectionLifeTime { get; set; }
        public System.Boolean? Pooling { get; set; }
        public System.UInt32? MinimumPoolSize { get; set; }
        public System.UInt32? MaximumPoolSize { get; set; }
        public System.Boolean? ConnectionReset { get; set; }
        public System.Boolean? CacheServerProperties { get; set; }
        public System.Boolean? TreatBlobsAsUTF8 { get; set; }
        public System.String? BlobAsUTF8IncludePattern { get; set; }
        public System.String? BlobAsUTF8ExcludePattern { get; set; }
        public System.Boolean? UseDefaultCommandTimeoutForEF { get; set; }
        public System.String? Server { get; set; }
        public System.String? Database { get; set; }
        public MySql.Data.MySqlClient.MySqlConnectionProtocol? ConnectionProtocol { get; set; }
        public System.UInt32? Port { get; set; }
        public System.Boolean? DnsSrv { get; set; }
        public System.String? UserID { get; set; }
        public System.String? Password { get; set; }
        public System.String? CertificateFile { get; set; }
        public System.String? CertificatePassword { get; set; }
        public MySql.Data.MySqlClient.MySqlCertificateStoreLocation? CertificateStoreLocation { get; set; }
        public System.String? CertificateThumbprint { get; set; }
        public MySql.Data.MySqlClient.MySqlSslMode? SslMode { get; set; }
        public System.String? SslCa { get; set; }
        public System.String? TlsVersion { get; set; }
        public System.String? SslKey { get; set; }
        public System.String? SslCert { get; set; }
        public System.String? SshHostName { get; set; }
        public System.UInt32? SshPort { get; set; }
        public System.String? SshUserName { get; set; }
        public System.String? SshPassword { get; set; }
        public System.String? SshKeyFile { get; set; }
        public System.String? SshPassphrase { get; set; }
        public System.UInt32? Keepalive { get; set; }
        public System.String? CharacterSet { get; set; }
    }
    class NpgsqlSettings
    {
        public System.String? Host { get; set; }
        public System.Int32? Port { get; set; }
        public System.String? Database { get; set; }
        public System.String? Username { get; set; }
        public System.String? Password { get; set; }
        public System.String? Passfile { get; set; }
        public System.String? ApplicationName { get; set; }
        public System.Boolean? Enlist { get; set; }
        public System.String? SearchPath { get; set; }
        public System.String? ClientEncoding { get; set; }
        public System.String? Encoding { get; set; }
        public System.String? Timezone { get; set; }
        public Npgsql.SslMode? SslMode { get; set; }
        public System.Boolean? TrustServerCertificate { get; set; }
        public System.String? ClientCertificate { get; set; }
        public System.String? ClientCertificateKey { get; set; }
        public System.String? RootCertificate { get; set; }
        public System.Boolean? CheckCertificateRevocation { get; set; }
        public System.Boolean? IntegratedSecurity { get; set; }
        public System.String? KerberosServiceName { get; set; }
        public System.Boolean? IncludeRealm { get; set; }
        public System.Boolean? PersistSecurityInfo { get; set; }
        public System.Boolean? LogParameters { get; set; }
        public System.Boolean? IncludeErrorDetails { get; set; }
        public System.Boolean? Pooling { get; set; }
        public System.Int32? MinPoolSize { get; set; }
        public System.Int32? MaxPoolSize { get; set; }
        public System.Int32? ConnectionIdleLifetime { get; set; }
        public System.Int32? ConnectionPruningInterval { get; set; }
        public System.Int32? ConnectionLifetime { get; set; }
        public System.Int32? Timeout { get; set; }
        public System.Int32? CommandTimeout { get; set; }
        public System.Int32? InternalCommandTimeout { get; set; }
        public System.Int32? CancellationTimeout { get; set; }
        public System.String? EntityTemplateDatabase { get; set; }
        public System.String? EntityAdminDatabase { get; set; }
        public System.Int32? KeepAlive { get; set; }
        public System.Boolean? TcpKeepAlive { get; set; }
        public System.Int32? TcpKeepAliveTime { get; set; }
        public System.Int32? TcpKeepAliveInterval { get; set; }
        public System.Int32? ReadBufferSize { get; set; }
        public System.Int32? WriteBufferSize { get; set; }
        public System.Int32? SocketReceiveBufferSize { get; set; }
        public System.Int32? SocketSendBufferSize { get; set; }
        public System.Int32? MaxAutoPrepare { get; set; }
        public System.Int32? AutoPrepareMinUsages { get; set; }
        public System.Boolean? NoResetOnClose { get; set; }
        public System.Boolean? LoadTableComposites { get; set; }
        public System.String? Options { get; set; }
        public System.Boolean? Multiplexing { get; set; }
        public System.Int32? WriteCoalescingDelayUs { get; set; }
        public System.Int32? WriteCoalescingBufferThresholdBytes { get; set; }
        public Npgsql.ServerCompatibilityMode? ServerCompatibilityMode { get; set; }
        public System.Boolean? ConvertInfinityDateTime { get; set; }
        public System.Boolean? ContinuousProcessing { get; set; }
        public System.Boolean? BackendTimeouts { get; set; }
        public System.Boolean? PreloadReader { get; set; }
        public System.Boolean? UseExtendedTypes { get; set; }
        public System.Boolean? UseSslStream { get; set; }
        public System.Boolean? UsePerfCounters { get; set; }
    }
}

